// ============================================================
// FlexMed v2 — Products Data
// Centralized product catalog — all product data lives here
// ============================================================

import type { Product } from './types'
import { SITE_SETTINGS } from './data-site'

const TRANSPARENT_CUTOUT_IMAGE_SLUGS = new Set([
  'epithalon-10mg',
  'glutathione-500',
  'glutathione-1000',
  'nad-plus-500',
  'nad-plus-1000',
  'snap-8-10mg',
  'tirz-30mg',
])

export const PLACEHOLDER_PRODUCT_IMAGE = '/products/front.png'
export const PLACEHOLDER_RENDER_SLUGS = [
  'aodc-5mg',
  '5-amino-1-50mg',
  'adalink',
  'adalink-amp',
  'adamax-10mg',
  'ara-290-10mg',
  'cartalax-20mg',
  'fox04-10mg',
  'glow-50-10-10',
  'hgh-12iu',
  'hgh-24iu',
  'hgh36-36iu',
  'igf-1-10mg',
  'livogen',
  'testogen-20mg',
  'kiss-10mg',
  'klow-50-10-10-10',
  'll-37-5mg',
  'mel-2-10mg',
  'mots-c-10mg',
  'pe-22-28-wwb-10mg',
  'pinealon-10mg',
  'bronchogen',
  'reta-20mg',
  'reta-30mg',
  'reta-40mg',
  'reta-50mg',
  'reta-60mg',
  'reta-10mg',
  'reta-15mg',
  'selank-10mg',
  'semax-10mg',
  'slu-pp-332-10mg',
  'slu-pp-332-30mg',
  'ss-31-10mg',
  'ss-31-5mg',
  'ss-31-30mg',
  'ss-31-40mg',
  'tc250-10ml',
  'tesamor-10mg',
  'tirz-10mg',
  'tirz-20mg',
  'tirz-40mg',
  'tirz-50mg',
  'vesugen-20mg',
  'vip-10mg',
  'wolver-bpc-tb500',
] as const

const PRODUCT_PRICING: Record<string, { priceVial?: string; priceKit?: string }> = {
  '5-amino-1-50mg': { priceVial: '$55' },
  'adalink': { priceVial: '$50' },
  'adamax-10mg': { priceVial: '$60' },
  'aodc-5mg': { priceVial: '$60' },
  'ara-290-10mg': { priceVial: '$35' },
  'bronchogen': { priceVial: '$70' },
  'cjc-ipa-10mg': { priceVial: '$40' },
  'cagri-5mg': { priceVial: '$35' },
  'cartalax-20mg': { priceVial: '$48' },
  'dsip-5mg': { priceVial: '$25' },
  'dsip-10mg': { priceVial: '$40' },
  'epithalon-10mg': { priceVial: '$40' },
  'epithalon-50mg': { priceVial: '$75' },
  'fox04-10mg': { priceVial: '$80' },
  'glow-50-10-10': { priceVial: '$80' },
  'glutathione-500': { priceVial: '$35' },
  'glutathione-1000': { priceVial: '$40' },
  'hgh36-36iu': { priceVial: '$55' },
  'igf-1-10mg': { priceVial: '$50' },
  'kiss-10mg': { priceVial: '$30' },
  'kpv-10mg': { priceVial: '$40' },
  'klow-50-10-10-10': { priceVial: '$80' },
  'lipo-c-20ml': { priceVial: '$55' },
  'livogen': { priceVial: '$65' },
  'll-37-5mg': { priceVial: '$40' },
  'mel-2-10mg': { priceVial: '$22' },
  'mots-c-10mg': { priceVial: '$30' },
  'mots-c-40mg': { priceVial: '$80' },
  'nad-plus-500': { priceVial: '$75' },
  'pe-22-28-wwb-10mg': { priceVial: '$45' },
  'pinealon-10mg': { priceVial: '$30' },
  'pnc-27-5mg': { priceVial: '$50' },
  'pt-141-10mg': { priceVial: '$30' },
  'reta-20mg': { priceVial: '$130' },
  'reta-30mg': { priceVial: '$150' },
  'selank-10mg': { priceVial: '$45' },
  'semax-10mg': { priceVial: '$40' },
  'slu-pp-332-10mg': { priceVial: '$75' },
  'snap-8-10mg': { priceVial: '$55' },
  'ss-31-10mg': { priceVial: '$45' },
  'ss-31-50mg': { priceVial: '$85' },
  'tesamor-10mg': { priceVial: '$50' },
  'testogen-20mg': { priceVial: '$70' },
  'thy-a1-10mg': { priceVial: '$40' },
  'tirz-10mg': { priceVial: '$100' },
  'tirz-15mg': { priceVial: '$115' },
  'tirz-20mg': { priceVial: '$120' },
  'tirz-30mg': { priceVial: '$130' },
  'tirz-40mg': { priceVial: '$140' },
  'vesugen-20mg': { priceVial: '$70' },
  'wolver-bpc-tb500': { priceVial: '$60' },
}

export const NEEDED_PRICES = [
] as const

function createCatalogProduct(input: {
  slug: string
  displayName: string
  fullName: string
  alias: string
  category: string
  researchCategory: string
  structureType: string
  strength: number
  unit: string
  formatType: string
  summaryShort: string
  summaryFull: string
  priceVial?: string
  priceKit?: string
  accentColor: string
  accentColorHex: string
  image?: string
  status?: Product['status']
  coaStatus?: Product['coaStatus']
  batchNumber?: string
  publishStatus?: Product['publishStatus']
  needsFounderConfirmation?: boolean
  notes?: string
  variantGroup?: string
  variantLabel?: string
}): Product {
  return {
    slug: input.slug,
    displayName: input.displayName,
    fullName: input.fullName,
    alias: input.alias,
    category: input.category,
    researchCategory: input.researchCategory,
    structureType: input.structureType,
    strength: input.strength,
    unit: input.unit,
    formatType: input.formatType,
    status: input.status ?? 'in_stock',
    coaStatus: input.coaStatus ?? 'pending',
    coaUrl: '',
    verificationUrl: '',
    batchNumber: input.batchNumber ?? '',
    testingLab: '',
    purityPercent: '',
    summaryShort: input.summaryShort,
    summaryFull: input.summaryFull,
    priceVial: input.priceVial ?? PRODUCT_PRICING[input.slug]?.priceVial,
    priceKit: input.priceKit ?? PRODUCT_PRICING[input.slug]?.priceKit,
    features: ['Standardized label format', 'Research-first presentation', 'COA-linked workflow'],
    accentColor: input.accentColor,
    accentColorHex: input.accentColorHex,
    image: input.image ?? PLACEHOLDER_PRODUCT_IMAGE,
    hoverSpinFrames: [],
    publishStatus: input.publishStatus ?? 'confirmed',
    needsFounderConfirmation: input.needsFounderConfirmation ?? false,
    notes: input.notes,
    variantGroup: input.variantGroup,
    variantLabel: input.variantLabel,
  }
}

// ─── Image Asset Mapping ─────────────────────────────────────
// Maps product slugs to their source files from the FLEXMED
// asset folder. 'front' is required for the catalog card and
// product detail hero. 'side' is optional alternate angle.
// 'hoverSpinFrames' can be added later without refactoring.
// ─────────────────────────────────────────────────────────────

export const PRODUCT_IMAGES: Record<string, { front: string; side?: string; hoverSpinFrames?: string[] }> = {
  '5-amino-1-50mg':    { front: '/products/5-amino-1-50mg/front.png' },
  'adamax-10mg':       { front: '/products/adamax-10mg/front.png' },
  'adalink':           { front: '/products/adalink/front.png' },
  'aodc-5mg':          { front: '/products/aodc-5mg/front.png' },
  'ara-290-10mg':      { front: '/products/ara-290-10mg/front.png' },
  'bronchogen':        { front: '/products/bronchogen/front.png' },
  'cartalax-20mg':     { front: '/products/cartalax-20mg/front.png' },
  'cagri-5mg':         { front: '/products/cagri-5mg/front.jpg' },
  'cjc-ipa-10mg':      { front: '/products/cjc-ipa-10mg/front.png' },
  'dsip-5mg':          { front: '/products/dsip-5mg/front.jpg' },
  'dsip-10mg':         { front: '/products/dsip-5mg/front.jpg' },
  'epithalon-10mg':    { front: '/products/epithalon-10mg/front.png', side: '/products/epithalon-10mg/side.png' },
  'epithalon-50mg':    { front: '/products/epithalon-10mg/front.png', side: '/products/epithalon-10mg/side.png' },
  'fox04-10mg':        { front: '/products/fox04-10mg/front.png' },
  'glow-50-10-10':     { front: '/products/glow-50-10-10/front.png' },
  'glutathione-500':   { front: '/products/glutathione-600/front.png' },
  'glutathione-1000':  { front: '/products/glutathione-1200/front.png' },
  'hgh-12iu':          { front: '/products/hgh-12iu/front.png' },
  'hgh-24iu':          { front: '/products/hgh-24iu/front.png' },
  'hgh36-36iu':        { front: '/products/hgh36-36iu/front.png' },
  'igf-1-10mg':        { front: '/products/igf-1-10mg/front.png' },
  'kiss-10mg':         { front: '/products/kiss-10mg/front.png' },
  'klow-50-10-10-10':  { front: '/products/klow-50-10-10-10/front.png' },
  'kpv-10mg':          { front: '/products/kpv-10mg/front.jpg' },
  'll-37-5mg':         { front: '/products/ll-37-5mg/front.png' },
  'livogen':           { front: '/products/livogen/front.png' },
  'testogen-20mg':     { front: '/products/front.png' },
  'mel-2-10mg':        { front: '/products/mel-2-10mg/front.png' },
  'mots-c-10mg':       { front: '/products/mots-c-10mg/front.png' },
  'mots-c-40mg':       { front: '/products/mots-c-40mg/front.jpg' },
  'nad-plus-500':       { front: '/products/nad-plus-500/front.png', side: '/products/nad-plus-500/side.png' },
  'nad-plus-1000':      { front: '/products/nad-plus-500/front.png', side: '/products/nad-plus-500/side.png' },
  'pe-22-28-wwb-10mg': { front: '/products/pe-22-28-wwb-10mg/front.png' },
  'pinealon-10mg':      { front: '/products/pinealon-10mg/front.png' },
  'pnc-27-5mg':        { front: '/products/pnc-27-5mg/front.jpg' },
  'primo100-10ml':     { front: '/products/primo100-10ml/front.png' },
  'pt-141-10mg':       { front: '/products/pt-141-10mg/front.jpg' },
  'reta-10mg':         { front: '/products/reta-20mg/front.png' },
  'reta-15mg':         { front: '/products/reta-20mg/front.png' },
  'reta-20mg':         { front: '/products/reta-20mg/front.png' },
  'reta-30mg':         { front: '/products/reta-30mg/front.png' },
  'reta-40mg':         { front: '/products/reta-30mg/front.png' },
  'reta-50mg':         { front: '/products/reta-30mg/front.png' },
  'reta-60mg':         { front: '/products/reta-30mg/front.png' },
  'selank-10mg':       { front: '/products/selank-10mg/front.png' },
  'semax-10mg':        { front: '/products/semax-10mg/front.png' },
  'slu-pp-332-10mg':   { front: '/products/slu-pp-3325mg/front.png' },
  'slu-pp-332-30mg':   { front: '/products/slu-pp-3325mg/front.png' },
  'snap-8-10mg':      { front: '/products/snap-8-10mg/front.png' },
  'ss-31-5mg':         { front: '/products/ss-31-50mg/front.png' },
  'ss-31-10mg':        { front: '/products/ss-31-10mg/front.png' },
  'ss-31-30mg':        { front: '/products/ss-31-50mg/front.png' },
  'ss-31-40mg':        { front: '/products/ss-31-50mg/front.png' },
  'ss-31-50mg':        { front: '/products/ss-31-50mg/front.png' },
  'tesamor-10mg':      { front: '/products/tesamor-10mg/front.png' },
  'thy-a1-10mg':       { front: '/products/thy-a1-10mg/front.jpg' },
  'tirz-10mg':         { front: '/products/tirz-10mg/front.png' },
  'tirz-15mg':         { front: '/products/tirz-15mg/front.jpg' },
  'tirz-20mg':         { front: '/products/tirz-10mg/front.png' },
  'tirz-30mg':         { front: '/products/tirz-30mg/front.png', side: '/products/tirz-30mg/side.png' },
  'tirz-40mg':         { front: '/products/tirz-30mg/front.png' },
  'tirz-50mg':         { front: '/products/tirz-30mg/front.png' },
  'vesugen-20mg':      { front: '/products/vesugen-20mg/front.png' },
  'vip-10mg':          { front: '/products/vip-10mg/front.png' },
  'wolver-bpc-tb500':  { front: '/products/wolver-bpc-tb500/front.png' },
}

export const PRODUCTS: Record<string, Product> = {

  // ─── CONFIRMED — BUILD NOW ───────────────────────────────────

  'cjc-ipa-10mg': {
    slug: 'cjc-ipa-10mg',
    displayName: 'CJC/Ipa 10mg',
    fullName: 'CJC-1295 + Ipamorelin',
    alias: 'CJC/Ipa',
    category: 'Endocrine Signaling Research',
    researchCategory: 'Endocrine Peptide Signaling Research',
    structureType: 'Synthetic peptide combination',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    status: 'in_stock',
    coaStatus: 'available',
    coaUrl: '',
    verificationUrl: '',
    batchNumber: 'FM-CJC-IPA-001',
    testingLab: '',
    purityPercent: '',
    priceVial: '$40',
    summaryShort: 'Research peptide combination commonly referenced in endocrine peptide signaling research.',
    summaryFull:
      'CJC-1295 (No-DAC) combined with Ipamorelin is commonly referenced in endocrine peptide signaling research and controlled assay design. This page is intended for cataloging and research-reference purposes only.',
    features: [
      'Standardized label format',
      'Research-first presentation',
      'COA-linked workflow',
    ],
    accentColor: 'cool cyan-blue',
    accentColorHex: '#6B9FBF',
    image: '/products/cjc-ipa-10mg/front.jpg',
    hoverSpinFrames: [],
    publishStatus: 'confirmed',
    needsFounderConfirmation: false,
  },

  'cagri-5mg': {
    slug: 'cagri-5mg',
    displayName: 'Cagri 5mg',
    fullName: 'Cagrillin',
    alias: 'Cagri',
    category: 'Metabolic Research',
    researchCategory: 'Amylin receptor research',
    structureType: 'Synthetic peptide analog',
    strength: 5,
    unit: 'mg',
    formatType: 'vial',
    status: 'in_stock',
    coaStatus: 'available',
    coaUrl: '',
    verificationUrl: '',
    batchNumber: 'FM-CAG-001',
    testingLab: '',
    purityPercent: '',
    priceVial: '$35',
    summaryShort: 'Research peptide analog commonly referenced in amylin receptor and metabolic signaling research.',
    summaryFull:
      'Cagrilintide is commonly referenced in metabolic and amylin receptor research involving signaling and pathway characterization. This page is intended for cataloging and research-reference purposes only.',
    features: [
      'Standardized label format',
      'Research-first presentation',
      'COA-linked workflow',
    ],
    accentColor: 'warm amber',
    accentColorHex: '#C4976A',
    image: '/products/cagri-5mg/front.jpg',
    hoverSpinFrames: [],
    publishStatus: 'confirmed',
    needsFounderConfirmation: false,
  },

  'dsip-5mg': {
    slug: 'dsip-5mg',
    displayName: 'DSIP 5mg',
    fullName: 'Delta Sleep-Inducing Peptide',
    alias: 'DSIP',
    category: 'Neuropeptide Research',
    researchCategory: 'Sleep and circadian rhythm research',
    structureType: 'Nonapeptide',
    strength: 5,
    unit: 'mg',
    formatType: 'vial',
    status: 'in_stock',
    coaStatus: 'available',
    coaUrl: '',
    verificationUrl: '',
    batchNumber: 'FM-DSP-001',
    testingLab: '',
    purityPercent: '',
    priceVial: '$25',
    summaryShort: 'Neuropeptide commonly referenced in circadian-rhythm and neuropeptide research.',
    summaryFull:
      'Delta Sleep-Inducing Peptide (DSIP) is commonly referenced in neuropeptide research involving circadian-rhythm and signaling pathways. This page is intended for cataloging and research-reference purposes only.',
    features: [
      'Standardized label format',
      'Research-first presentation',
      'COA-linked workflow',
    ],
    accentColor: 'soft indigo',
    accentColorHex: '#8B8FC7',
    image: '/products/dsip-5mg/front.jpg',
    hoverSpinFrames: [],
    publishStatus: 'confirmed',
    needsFounderConfirmation: false,
    variantGroup: 'dsip',
    variantLabel: '5mg',
  },

  'dsip-10mg': createCatalogProduct({
    slug: 'dsip-10mg',
    displayName: 'DSIP 10mg',
    fullName: 'Delta Sleep-Inducing Peptide',
    alias: 'DSIP',
    category: 'Neuropeptide Research',
    researchCategory: 'Sleep and circadian rhythm research',
    structureType: 'Nonapeptide',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    summaryShort: 'Neuropeptide commonly referenced in circadian-rhythm and neuropeptide research.',
    summaryFull:
      'Delta Sleep-Inducing Peptide (DSIP) is commonly referenced in neuropeptide research involving circadian-rhythm and signaling pathways. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'soft indigo',
    accentColorHex: '#8B8FC7',
    variantGroup: 'dsip',
    variantLabel: '10mg',
  }),

  'epithalon-10mg': {
    slug: 'epithalon-10mg',
    displayName: 'Epithalon 10mg',
    fullName: 'Epithalon',
    alias: 'Epithalon',
    category: 'Telomere Research',
    researchCategory: 'Telomere biology and cellular aging research',
    structureType: 'Tetrapeptide',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    status: 'in_stock',
    coaStatus: 'available',
    coaUrl: '',
    verificationUrl: '',
    batchNumber: 'FM-EPT-001',
    testingLab: '',
    purityPercent: '',
    priceVial: '$40',
    summaryShort: 'Tetrapeptide commonly grouped in telomere biology and cellular aging research.',
    summaryFull:
      'Epithalon is generally classified in telomere biology and cellular-aging research catalogs. This page is intended for cataloging and research-reference purposes only.',
    features: [
      'Standardized label format',
      'Research-first presentation',
      'COA-linked workflow',
    ],
    accentColor: 'muted silver',
    accentColorHex: '#9EAAB4',
    image: '/products/epithalon-10mg/front.png',
    hoverSpinFrames: [],
    publishStatus: 'confirmed',
    needsFounderConfirmation: false,
    variantGroup: 'epithalon',
    variantLabel: '10mg',
  },

  'epithalon-50mg': createCatalogProduct({
    slug: 'epithalon-50mg',
    displayName: 'Epithalon 50mg',
    fullName: 'Epithalon',
    alias: 'Epithalon',
    category: 'Telomere Research',
    researchCategory: 'Telomere biology and cellular aging research',
    structureType: 'Tetrapeptide',
    strength: 50,
    unit: 'mg',
    formatType: 'vial',
    summaryShort: 'Tetrapeptide commonly grouped in telomere biology and cellular aging research.',
    summaryFull:
      'Epithalon is generally classified in telomere biology and cellular-aging research catalogs. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'muted silver',
    accentColorHex: '#9EAAB4',
    variantGroup: 'epithalon',
    variantLabel: '50mg',
  }),

  'glutathione-500': {
    slug: 'glutathione-500',
    displayName: 'Glutathione 1200mg',
    fullName: 'Glutathione',
    alias: 'GSH',
    category: 'Antioxidant Research',
    researchCategory: 'Cellular antioxidant defense research',
    structureType: 'Tripeptide',
    strength: 1200,
    unit: 'mg',
    formatType: 'vial',
    status: 'in_stock',
    coaStatus: 'pending',
    coaUrl: '',
    verificationUrl: '',
    batchNumber: 'FM-GSH-1200-001',
    testingLab: '',
    purityPercent: '',
    summaryShort: 'Tripeptide commonly grouped in cellular antioxidant defense research.',
    summaryFull:
      'Glutathione (GSH) is generally classified in antioxidant and redox biology research catalogs. This page is intended for cataloging and research-reference purposes only.',
    features: [
      'Standardized label format',
      'Research-first presentation',
      'COA-linked workflow',
    ],
    accentColor: 'sage green',
    accentColorHex: '#7A9E7E',
    priceVial: '$35',
    image: '/products/glutathione-600/front.png',
    hoverSpinFrames: [],
    publishStatus: 'confirmed',
    needsFounderConfirmation: false,
    variantGroup: 'glutathione',
    variantLabel: '1200mg',
  },

  'glutathione-1000': {
    slug: 'glutathione-1000',
    displayName: 'Glutathione 1500mg',
    fullName: 'Glutathione',
    alias: 'GSH',
    category: 'Antioxidant Research',
    researchCategory: 'Cellular antioxidant defense research',
    structureType: 'Tripeptide',
    strength: 1500,
    unit: 'mg',
    formatType: 'vial',
    status: 'in_stock',
    coaStatus: 'pending',
    coaUrl: '',
    verificationUrl: '',
    batchNumber: 'FM-GSH-1500-001',
    testingLab: '',
    purityPercent: '',
    summaryShort: 'Tripeptide commonly grouped in cellular antioxidant defense research.',
    summaryFull:
      'Glutathione (GSH) is generally classified in antioxidant and redox biology research catalogs. This page is intended for cataloging and research-reference purposes only.',
    features: [
      'Standardized label format',
      'Research-first presentation',
      'COA-linked workflow',
    ],
    accentColor: 'sage green',
    accentColorHex: '#7A9E7E',
    priceVial: '$40',
    image: '/products/glutathione-1200/front.png',
    hoverSpinFrames: [],
    publishStatus: 'confirmed',
    needsFounderConfirmation: false,
    variantGroup: 'glutathione',
    variantLabel: '1500mg',
  },

  'kpv-10mg': {
    slug: 'kpv-10mg',
    displayName: 'KPV 10mg',
    fullName: 'Lysine-Proline-Valine',
    alias: 'KPV',
    category: 'Inflammatory Research',
    researchCategory: 'Anti-inflammatory peptide research',
    structureType: 'Tripeptide',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    status: 'in_stock',
    coaStatus: 'pending',
    coaUrl: '',
    verificationUrl: '',
    batchNumber: 'FM-KPV-001',
    testingLab: '',
    purityPercent: '',
    priceVial: '$40',
    summaryShort: 'Tripeptide commonly referenced in inflammatory signaling and epithelial-barrier research.',
    summaryFull:
      'KPV (Lysine-Proline-Valine) is commonly referenced in research focused on inflammatory signaling, epithelial-barrier work, and immune-response pathways. This page is intended for cataloging and research-reference purposes only.',
    features: [
      'Standardized label format',
      'Research-first presentation',
      'COA-linked workflow',
    ],
    accentColor: 'cool slate',
    accentColorHex: '#7A8FA0',
    image: '/products/kpv-10mg/front.jpg',
    hoverSpinFrames: [],
    publishStatus: 'confirmed',
    needsFounderConfirmation: false,
  },

  'mots-c-40mg': {
    slug: 'mots-c-40mg',
    displayName: 'Mots-C 40mg',
    fullName: 'Mots-C',
    alias: 'Mots-C',
    category: 'Mitochondrial Research',
    researchCategory: 'Mitochondrial peptide and metabolic research',
    structureType: 'Mitochondrial-encoded peptide',
    strength: 40,
    unit: 'mg',
    formatType: 'vial',
    status: 'in_stock',
    coaStatus: 'available',
    coaUrl: '',
    verificationUrl: '',
    batchNumber: 'FM-MTC-001',
    testingLab: '',
    purityPercent: '',
    priceVial: '$80',
    summaryShort: 'Mitochondrial peptide commonly referenced in mitochondrial signaling and metabolic research.',
    summaryFull:
      'MOTS-C is commonly referenced in mitochondrial and metabolic research involving cellular energy and signaling pathways. This page is intended for cataloging and research-reference purposes only.',
    features: [
      'Standardized label format',
      'Research-first presentation',
      'COA-linked workflow',
    ],
    accentColor: 'deep teal',
    accentColorHex: '#4A7A7A',
    image: '/products/mots-c-40mg/front.jpg',
    hoverSpinFrames: [],
    publishStatus: 'confirmed',
    needsFounderConfirmation: false,
    variantGroup: 'motsc',
    variantLabel: '40mg',
  },

  'nad-plus-500': {
    slug: 'nad-plus-500',
    displayName: 'NAD+ 500mg',
    fullName: 'Nicotinamide Adenine Dinucleotide',
    alias: 'NAD+',
    category: 'Cellular Health Research',
    researchCategory: 'NAD+ biosynthetic and cellular health research',
    structureType: 'Dinucleotide',
    strength: 500,
    unit: 'mg',
    formatType: 'vial',
    status: 'in_stock',
    coaStatus: 'available',
    coaUrl: '',
    verificationUrl: '',
    batchNumber: 'FM-NAD-500-001',
    testingLab: '',
    purityPercent: '',
    priceVial: '$75',
    summaryShort: 'Dinucleotide commonly grouped in NAD+ biosynthetic and cellular health research.',
    summaryFull:
      'Nicotinamide Adenine Dinucleotide (NAD+) is generally classified in cellular health, metabolism, and sirtuin biology research catalogs. This page is intended for cataloging and research-reference purposes only.',
    features: [
      'Standardized label format',
      'Research-first presentation',
      'COA-linked workflow',
    ],
    accentColor: 'warm ivory',
    accentColorHex: '#C4B89A',
    image: '/products/nad-plus-500/front.png',
    hoverSpinFrames: [],
    publishStatus: 'confirmed',
    needsFounderConfirmation: false,
    variantGroup: 'nadplus',
    variantLabel: '500mg',
  },

  'nad-plus-1000': {
    slug: 'nad-plus-1000',
    displayName: 'NAD+ 1000mg',
    fullName: 'Nicotinamide Adenine Dinucleotide',
    alias: 'NAD+',
    category: 'Cellular Health Research',
    researchCategory: 'NAD+ biosynthetic and cellular health research',
    structureType: 'Dinucleotide',
    strength: 1000,
    unit: 'mg',
    formatType: 'vial',
    status: 'incoming',
    coaStatus: 'pending',
    coaUrl: '',
    verificationUrl: '',
    batchNumber: '',
    testingLab: '',
    purityPercent: '',
    summaryShort: 'Dinucleotide commonly grouped in NAD+ biosynthetic and cellular health research.',
    summaryFull:
      'Nicotinamide Adenine Dinucleotide (NAD+) is generally classified in cellular health, metabolism, and sirtuin biology research catalogs. This page is intended for cataloging and research-reference purposes only.',
    features: [
      'Standardized label format',
      'Research-first presentation',
      'COA-linked workflow',
    ],
    accentColor: 'warm ivory',
    accentColorHex: '#C4B89A',
    image: '/products/nad-plus-500/front.png',
    hoverSpinFrames: [],
    publishStatus: 'confirmed',
    needsFounderConfirmation: false,
    variantGroup: 'nadplus',
    variantLabel: '1000mg',
  },

  'pnc-27-5mg': {
    slug: 'pnc-27-5mg',
    displayName: 'PNC-27 5mg',
    fullName: 'PNC-27',
    alias: 'PNC-27',
    category: 'Cell Cycle Research',
    researchCategory: 'Cell cycle and proliferative research',
    structureType: 'Helical peptide',
    strength: 5,
    unit: 'mg',
    formatType: 'vial',
    status: 'in_stock',
    coaStatus: 'pending',
    coaUrl: '',
    verificationUrl: '',
    batchNumber: 'FM-PNC-001',
    testingLab: '',
    purityPercent: '',
    summaryShort: 'Helical peptide commonly grouped in cell cycle and proliferative research.',
    summaryFull:
      'PNC-27 is generally classified in cell cycle, oncology, and proliferative research catalogs. This page is intended for cataloging and research-reference purposes only.',
    features: [
      'Standardized label format',
      'Research-first presentation',
      'COA-linked workflow',
    ],
    accentColor: 'rose taupe',
    accentColorHex: '#B08080',
    image: '/products/pnc-27-5mg/front.jpg',
    hoverSpinFrames: [],
    publishStatus: 'needs_confirmation',
    needsFounderConfirmation: true,
    /**
     * TIER 1: Oncology-associated peptide — founder review required before
     * any public-facing presence even after publishStatus='confirmed'.
     */
    riskTier: 'tier1_everything',
    notes: 'Oncology-associated compound. Awaiting founder review before public catalog visibility.',
  },

  'pt-141-10mg': {
    slug: 'pt-141-10mg',
    displayName: 'PT-141 10mg',
    fullName: 'PT-141 (Bremelanotide)',
    alias: 'PT-141',
    category: 'Neuropeptide Research',
    researchCategory: 'Melanocortin receptor research',
    structureType: 'Cyclic heptapeptide',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    status: 'in_stock',
    coaStatus: 'pending',
    coaUrl: '',
    verificationUrl: '',
    batchNumber: 'FM-PT-001',
    testingLab: '',
    purityPercent: '',
    summaryShort: 'Cyclic heptapeptide commonly grouped in melanocortin receptor research.',
    summaryFull:
      'PT-141 (Bremelanotide) is generally classified in melanocortin and neuropeptide research catalogs. This page is intended for cataloging and research-reference purposes only.',
    features: [
      'Standardized label format',
      'Research-first presentation',
      'COA-linked workflow',
    ],
    accentColor: 'deep burgundy',
    accentColorHex: '#8B4A5A',
    image: '/products/pt-141-10mg/front.jpg',
    hoverSpinFrames: [],
    publishStatus: 'needs_confirmation',
    needsFounderConfirmation: true,
    /**
     * TIER 1: Bremelanotide — CNS/sexual arousal mechanism, abuse-potential
     * concern in recreational contexts. Requires founder review before public
     * catalog visibility even with publishStatus='confirmed'.
     */
    riskTier: 'tier1_everything',
    notes: 'Melanocortin receptor compound with abuse-potential concern in recreational contexts. Awaiting founder review before public catalog visibility.',
  },

  'snap-8-10mg': {
    slug: 'snap-8-10mg',
    displayName: 'SNAP-8 10mg',
    fullName: 'SNAP-8',
    alias: 'SNAP-8',
    category: 'Dermatological Research',
    researchCategory: 'Neuropeptide and skin barrier research',
    structureType: 'Octapeptide',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    status: 'in_stock',
    coaStatus: 'pending',
    coaUrl: '',
    verificationUrl: '',
    batchNumber: 'FM-SNP-001',
    testingLab: '',
    purityPercent: '',
    priceVial: '$55',
    summaryShort: 'Octapeptide commonly grouped in dermatological and skin barrier research.',
    summaryFull:
      'SNAP-8 is generally classified in dermatological and skin barrier research catalogs. This page is intended for cataloging and research-reference purposes only.',
    features: [
      'Standardized label format',
      'Research-first presentation',
      'COA-linked workflow',
    ],
    accentColor: 'soft lavender',
    accentColorHex: '#9A8FC4',
    image: '/products/snap-8-10mg/front.png',
    hoverSpinFrames: [],
    publishStatus: 'confirmed',
    needsFounderConfirmation: false,
  },

  'ss-31-50mg': {
    slug: 'ss-31-50mg',
    displayName: 'SS-31 50mg',
    fullName: 'SS-31 (Elamipretide)',
    alias: 'SS-31',
    category: 'Mitochondrial Research',
    researchCategory: 'Mitochondrial targeting and cardiac research',
    structureType: 'Short cationic peptide',
    strength: 50,
    unit: 'mg',
    formatType: 'vial',
    status: 'in_stock',
    coaStatus: 'pending',
    coaUrl: '',
    verificationUrl: '',
    batchNumber: 'FM-SS31-001',
    testingLab: '',
    purityPercent: '',
    priceVial: '$85',
    summaryShort: 'Mitochondrial-targeting peptide commonly referenced in energy-production and oxidative-stress research.',
    summaryFull:
      'SS-31 (Elamipretide) is commonly referenced in mitochondrial research involving energy production and oxidative-stress pathways. This page is intended for cataloging and research-reference purposes only.',
    features: [
      'Standardized label format',
      'Research-first presentation',
      'COA-linked workflow',
    ],
    accentColor: 'forest teal',
    accentColorHex: '#3A6A6A',
    image: '/products/ss-31-50mg/front.png',
    hoverSpinFrames: [],
    publishStatus: 'confirmed',
    needsFounderConfirmation: false,
    variantGroup: 'ss31',
    variantLabel: '50mg',
  },

  'thy-a1-10mg': {
    slug: 'thy-a1-10mg',
    displayName: 'TA-1 10mg',
    fullName: 'Thymosin Alpha-1',
    alias: 'TA-1',
    category: 'Immunomodulation Research',
    researchCategory: 'Immune modulation and thymic peptide research',
    structureType: 'Polypeptide',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    status: 'in_stock',
    coaStatus: 'available',
    coaUrl: '',
    verificationUrl: '',
    batchNumber: 'FM-THA-001',
    testingLab: '',
    purityPercent: '',
    priceVial: '$40',
    summaryShort: 'Polypeptide commonly referenced in immune modulation and thymic peptide research.',
    summaryFull:
      'Thymosin Alpha-1 (THY-A1) is commonly referenced in immunomodulation research involving immune function and infection-response pathways. This page is intended for cataloging and research-reference purposes only.',
    features: [
      'Standardized label format',
      'Research-first presentation',
      'COA-linked workflow',
    ],
    accentColor: 'pearl white',
    accentColorHex: '#C8C4BC',
    image: '/products/thy-a1-10mg/front.jpg',
    hoverSpinFrames: [],
    publishStatus: 'confirmed',
    needsFounderConfirmation: false,
  },

  'tirz-15mg': {
    slug: 'tirz-15mg',
    displayName: 'TIRZ 15mg',
    fullName: 'Tirzepatide',
    alias: 'TIRZ',
    category: 'Metabolic Research',
    researchCategory: 'Dual incretin receptor research',
    structureType: 'Synthetic peptide analog',
    strength: 15,
    unit: 'mg',
    formatType: 'vial',
    status: 'in_stock',
    coaStatus: 'available',
    coaUrl: '',
    verificationUrl: '',
    batchNumber: 'FM-TZ-1501',
    testingLab: '',
    purityPercent: '',
    priceVial: '$115',
    summaryShort: 'Synthetic peptide analog commonly referenced in dual incretin receptor and metabolic research.',
    summaryFull:
      'Tirzepatide is commonly referenced in metabolic and incretin receptor research involving signaling and pathway characterization. This page is intended for cataloging and research-reference purposes only.',
    features: [
      'Standardized label format',
      'Research-first presentation',
      'COA-linked workflow',
    ],
    accentColor: 'cool cyan-blue',
    accentColorHex: '#4A8FC4',
    image: '/products/tirz-15mg/front.jpg',
    hoverSpinFrames: [],
    publishStatus: 'confirmed',
    needsFounderConfirmation: false,
    variantGroup: 'tirz',
    variantLabel: '15mg',
  },

  'tirz-30mg': {
    slug: 'tirz-30mg',
    displayName: 'TIRZ 30mg',
    fullName: 'Tirzepatide',
    alias: 'TIRZ',
    category: 'Metabolic Research',
    researchCategory: 'Dual incretin receptor research',
    structureType: 'Synthetic peptide analog',
    strength: 30,
    unit: 'mg',
    formatType: 'vial',
    status: 'in_stock',
    coaStatus: 'pending',
    coaUrl: '',
    verificationUrl: '',
    batchNumber: 'FM-TZ-3001',
    testingLab: '',
    purityPercent: '',
    priceVial: '$130',
    summaryShort: 'Synthetic peptide analog commonly grouped in dual incretin receptor research.',
    summaryFull:
      'Tirzepatide is generally classified in metabolic and incretin receptor research catalogs. This page is intended for cataloging and research-reference purposes only.',
    features: [
      'Standardized label format',
      'Research-first presentation',
      'COA-linked workflow',
    ],
    accentColor: 'cool cyan-blue',
    accentColorHex: '#4A8FC4',
    image: '/products/tirz-30mg/front.png',
    hoverSpinFrames: [],
    publishStatus: 'confirmed',
    needsFounderConfirmation: false,
    variantGroup: 'tirz',
    variantLabel: '30mg',
  },

  // ─── FOUNDER-SOURCED EXPANSION ITEMS ─────────────────────────
  // These entries came from the founder source sheet. Some are live
  // immediately, while higher-risk items remain in pending confirmation.

  'aodc-5mg': {
    slug: 'aodc-5mg',
    displayName: 'AODC-9604 10mg',
    fullName: 'AODC-9604',
    alias: 'AODC-9604',
    category: 'Metabolic Research',
    researchCategory: 'Lipid metabolism and adipocyte research',
    structureType: 'Synthetic peptide fragment',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    status: 'in_stock',
    coaStatus: 'pending',
    coaUrl: '',
    verificationUrl: '',
    batchNumber: '',
    testingLab: '',
    purityPercent: '',
    priceVial: '$60',
    summaryShort: 'Synthetic peptide fragment commonly referenced in lipid-metabolism and adipocyte research.',
    summaryFull:
      'AODC-9604 is commonly referenced in metabolic research involving lipid metabolism and adipocyte-signaling pathways. This page is intended for cataloging and research-reference purposes only.',
    features: ['Standardized label format', 'Research-first presentation'],
    accentColor: 'warm sand',
    accentColorHex: '#C4A882',
    image: '/products/aodc-5mg/front.png',
    hoverSpinFrames: [],
    publishStatus: 'confirmed',
    needsFounderConfirmation: false,
    notes: 'Founder-sourced catalog expansion item.',
  },

  'mel-2-10mg': {
    slug: 'mel-2-10mg',
    displayName: 'Melanotan II 10mg',
    fullName: 'Melanotan II',
    alias: 'MEL-2',
    category: 'Pigmentation Research',
    researchCategory: 'Melanocortin and pigmentation research',
    structureType: 'Cyclic heptapeptide',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    status: 'in_stock',
    coaStatus: 'pending',
    coaUrl: '',
    verificationUrl: '',
    batchNumber: '',
    testingLab: '',
    purityPercent: '',
    priceVial: '$22',
    summaryShort: 'Cyclic heptapeptide commonly referenced in melanocortin and pigmentation research.',
    summaryFull:
      'Melanotan II is listed in the founder source sheet for research involving pigmentation and melanocortin-related pathways. This page is intended for cataloging and research-reference purposes only.',
    features: ['Standardized label format', 'Research-first presentation'],
    accentColor: 'deep umber',
    accentColorHex: '#7A5030',
    image: '/products/mel-2-10mg/front.png',
    hoverSpinFrames: [],
    publishStatus: 'confirmed',
    needsFounderConfirmation: false,
    notes: 'Founder-sourced catalog expansion item.',
  },

  'pe-22-28-wwb-10mg': {
    slug: 'pe-22-28-wwb-10mg',
    displayName: 'PE 22-28 10mg',
    fullName: 'PE-22-28',
    alias: 'PE-22-28',
    category: 'Neuropeptide Research',
    researchCategory: 'Neuronal and neuropeptide receptor research',
    structureType: 'Oligopeptide',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    status: 'in_stock',
    coaStatus: 'pending',
    coaUrl: '',
    verificationUrl: '',
    batchNumber: '',
    testingLab: '',
    purityPercent: '',
    priceVial: '$45',
    summaryShort: 'Oligopeptide commonly grouped in neuropeptide receptor research.',
    summaryFull:
      'PE-22-28 is generally classified in neuronal and neuropeptide receptor research catalogs. This page is intended for cataloging and research-reference purposes only.',
    features: ['Standardized label format', 'Research-first presentation'],
    accentColor: 'muted violet',
    accentColorHex: '#7A6A9A',
    image: '/products/pe-22-28-wwb-10mg/front.png',
    hoverSpinFrames: [],
    publishStatus: 'confirmed',
    needsFounderConfirmation: false,
    notes: 'Placeholder render active until final product art is added.',
  },

  'reta-20mg': {
    slug: 'reta-20mg',
    displayName: 'Reta 20mg',
    fullName: 'Retatrutide',
    alias: 'RETA',
    category: 'Metabolic Research',
    researchCategory: 'GLP-1 / GIP / glucagon receptor research',
    structureType: 'Synthetic peptide analog',
    strength: 20,
    unit: 'mg',
    formatType: 'vial',
    status: 'in_stock',
    coaStatus: 'pending',
    coaUrl: '',
    verificationUrl: '',
    batchNumber: '',
    testingLab: '',
    purityPercent: '',
    priceVial: '$130',
    summaryShort: 'Synthetic peptide analog commonly grouped in GLP-1 / GIP / glucagon receptor research.',
    summaryFull:
      'Retatrutide is generally classified in metabolic and multi-receptor agonist research catalogs. This page is intended for cataloging and research-reference purposes only.',
    features: ['Standardized label format', 'Research-first presentation'],
    accentColor: 'cool slate blue',
    accentColorHex: '#5A7A9A',
    image: '/products/reta-20mg/front.png',
    hoverSpinFrames: [],
    publishStatus: 'confirmed',
    needsFounderConfirmation: false,
    notes: 'Founder-sourced catalog expansion item.',
    variantGroup: 'reta',
    variantLabel: '20mg',
  },

  'reta-30mg': {
    slug: 'reta-30mg',
    displayName: 'Reta 30mg',
    fullName: 'Retatrutide',
    alias: 'RETA',
    category: 'Metabolic Research',
    researchCategory: 'GLP-1 / GIP / glucagon receptor research',
    structureType: 'Synthetic peptide analog',
    strength: 30,
    unit: 'mg',
    formatType: 'vial',
    status: 'in_stock',
    coaStatus: 'pending',
    coaUrl: '',
    verificationUrl: '',
    batchNumber: '',
    testingLab: '',
    purityPercent: '',
    priceVial: '$150',
    summaryShort: 'Synthetic peptide analog commonly grouped in GLP-1 / GIP / glucagon receptor research.',
    summaryFull:
      'Retatrutide is generally classified in metabolic and multi-receptor agonist research catalogs. This page is intended for cataloging and research-reference purposes only.',
    features: ['Standardized label format', 'Research-first presentation'],
    accentColor: 'cool slate blue',
    accentColorHex: '#5A7A9A',
    image: '/products/reta-30mg/front.png',
    hoverSpinFrames: [],
    publishStatus: 'confirmed',
    needsFounderConfirmation: false,
    notes: 'Founder-sourced catalog expansion item.',
    variantGroup: 'reta',
    variantLabel: '30mg',
  },

  'reta-10mg': createCatalogProduct({
    slug: 'reta-10mg',
    displayName: 'Reta 10mg',
    fullName: 'Retatrutide',
    alias: 'RETA',
    category: 'Metabolic Research',
    researchCategory: 'GLP-1 / GIP / glucagon receptor research',
    structureType: 'Synthetic peptide analog',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    status: 'incoming',
    summaryShort: 'Synthetic peptide analog commonly grouped in GLP-1 / GIP / glucagon receptor research.',
    summaryFull: 'Retatrutide is generally classified in metabolic and multi-receptor agonist research catalogs. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'cool slate blue',
    accentColorHex: '#5A7A9A',
    variantGroup: 'reta',
    variantLabel: '10mg',
  }),

  'reta-15mg': createCatalogProduct({
    slug: 'reta-15mg',
    displayName: 'Reta 15mg',
    fullName: 'Retatrutide',
    alias: 'RETA',
    category: 'Metabolic Research',
    researchCategory: 'GLP-1 / GIP / glucagon receptor research',
    structureType: 'Synthetic peptide analog',
    strength: 15,
    unit: 'mg',
    formatType: 'vial',
    status: 'incoming',
    summaryShort: 'Synthetic peptide analog commonly grouped in GLP-1 / GIP / glucagon receptor research.',
    summaryFull: 'Retatrutide is generally classified in metabolic and multi-receptor agonist research catalogs. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'cool slate blue',
    accentColorHex: '#5A7A9A',
    variantGroup: 'reta',
    variantLabel: '15mg',
  }),

  'reta-40mg': createCatalogProduct({
    slug: 'reta-40mg',
    displayName: 'Reta 40mg',
    fullName: 'Retatrutide',
    alias: 'RETA',
    category: 'Metabolic Research',
    researchCategory: 'GLP-1 / GIP / glucagon receptor research',
    structureType: 'Synthetic peptide analog',
    strength: 40,
    unit: 'mg',
    formatType: 'vial',
    status: 'incoming',
    summaryShort: 'Synthetic peptide analog commonly grouped in GLP-1 / GIP / glucagon receptor research.',
    summaryFull: 'Retatrutide is generally classified in metabolic and multi-receptor agonist research catalogs. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'cool slate blue',
    accentColorHex: '#5A7A9A',
    variantGroup: 'reta',
    variantLabel: '40mg',
  }),

  'reta-50mg': createCatalogProduct({
    slug: 'reta-50mg',
    displayName: 'Reta 50mg',
    fullName: 'Retatrutide',
    alias: 'RETA',
    category: 'Metabolic Research',
    researchCategory: 'GLP-1 / GIP / glucagon receptor research',
    structureType: 'Synthetic peptide analog',
    strength: 50,
    unit: 'mg',
    formatType: 'vial',
    status: 'incoming',
    summaryShort: 'Synthetic peptide analog commonly grouped in GLP-1 / GIP / glucagon receptor research.',
    summaryFull: 'Retatrutide is generally classified in metabolic and multi-receptor agonist research catalogs. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'cool slate blue',
    accentColorHex: '#5A7A9A',
    variantGroup: 'reta',
    variantLabel: '50mg',
  }),

  'reta-60mg': createCatalogProduct({
    slug: 'reta-60mg',
    displayName: 'Reta 60mg',
    fullName: 'Retatrutide',
    alias: 'RETA',
    category: 'Metabolic Research',
    researchCategory: 'GLP-1 / GIP / glucagon receptor research',
    structureType: 'Synthetic peptide analog',
    strength: 60,
    unit: 'mg',
    formatType: 'vial',
    status: 'incoming',
    summaryShort: 'Synthetic peptide analog commonly grouped in GLP-1 / GIP / glucagon receptor research.',
    summaryFull: 'Retatrutide is generally classified in metabolic and multi-receptor agonist research catalogs. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'cool slate blue',
    accentColorHex: '#5A7A9A',
    variantGroup: 'reta',
    variantLabel: '60mg',
  }),

  '5-amino-1-50mg': createCatalogProduct({
    slug: '5-amino-1-50mg',
    displayName: '5 Amino 1 50mg',
    fullName: '5-Amino-1MQ',
    alias: '5 Amino 1',
    category: 'Metabolic Research',
    researchCategory: 'Metabolism and insulin-sensitivity research',
    structureType: 'Small molecule research compound',
    strength: 50,
    unit: 'mg',
    formatType: 'vial',
    summaryShort: 'Research compound referenced for metabolic-pathway and insulin-sensitivity research.',
    summaryFull: '5-Amino-1MQ is listed in the founder source sheet for research related to metabolic pathways and insulin sensitivity. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'graphite blue',
    accentColorHex: '#60708A',
  }),

  'adalink': createCatalogProduct({
    slug: 'adalink',
    displayName: 'Adalank 10mg',
    fullName: 'Adalank',
    alias: 'Adalank',
    category: 'Neuropeptide Research',
    researchCategory: 'Cognitive function and mood research',
    structureType: 'Research peptide',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    summaryShort: 'Research peptide referenced for cognitive-function and neurobehavioral signaling research.',
    summaryFull: 'Adalank is listed in the founder source sheet for research involving cognitive-function and neurobehavioral signaling pathways. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'clear teal',
    accentColorHex: '#5E9FA3',
  }),

  'adalink-amp': createCatalogProduct({
    slug: 'adalink-amp',
    displayName: 'Adalank Ampoule',
    fullName: 'Adalank',
    alias: 'Adalank',
    category: 'Neuropeptide Research',
    researchCategory: 'Cognitive function and mood research',
    structureType: 'Research peptide',
    strength: 0,
    unit: 'mg',
    formatType: 'ampoule',
    summaryShort: 'Ampoule-format listing for Adalank research programs involving cognitive-function and neurobehavioral studies.',
    summaryFull: 'This Adalank ampoule-format listing is included for research cataloging and documentation. It is intended for scientific and laboratory reference only.',
    accentColor: 'clear teal',
    accentColorHex: '#5E9FA3',
  }),

  'adamax-10mg': createCatalogProduct({
    slug: 'adamax-10mg',
    displayName: 'Adamax 10mg',
    fullName: 'Adamax',
    alias: 'Adamax',
    category: 'Neuropeptide Research',
    researchCategory: 'Cognitive enhancement and neuroprotection research',
    structureType: 'Research peptide',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    summaryShort: 'Research peptide referenced for cognitive enhancement, neuroprotection, and BDNF-related studies.',
    summaryFull: 'Adamax is listed in the founder source sheet for research involving cognitive ability, neuroprotection, and BDNF-related brain-health pathways. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'glacier blue',
    accentColorHex: '#6D98BF',
  }),

  'ara-290-10mg': createCatalogProduct({
    slug: 'ara-290-10mg',
    displayName: 'ARA-290 10mg',
    fullName: 'ARA-290',
    alias: 'ARA-290',
    category: 'Inflammatory Research',
    researchCategory: 'Neuropathy and tissue-repair research',
    structureType: 'Peptide analog',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    summaryShort: 'Peptide analog referenced for small-fiber nerve regeneration and neuropathic-pain research.',
    summaryFull: 'ARA-290 is listed in the founder source sheet for research involving small-fiber nerve regeneration and neuropathic-pain support. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'dusty cyan',
    accentColorHex: '#6C97A1',
  }),

  'cartalax-20mg': createCatalogProduct({
    slug: 'cartalax-20mg',
    displayName: 'Cartalax 20mg',
    fullName: 'Cartalax',
    alias: 'Cartalax',
    category: 'Bio-Regulator Research',
    researchCategory: 'Peptide bioregulator research',
    structureType: 'Peptide bioregulator',
    strength: 20,
    unit: 'mg',
    formatType: 'vial',
    status: 'incoming',
    summaryShort: 'Peptide bioregulator listed for connective-tissue and laboratory reference research.',
    summaryFull: 'Cartalax is currently grouped in the FlexMed bio-regulator catalog as a 20mg incoming research listing for scientific cataloging and laboratory reference only.',
    accentColor: 'sage aqua',
    accentColorHex: '#7AA59A',
  }),

  'dr-lipo-plus': createCatalogProduct({
    slug: 'dr-lipo-plus',
    displayName: 'Dr Lipo+',
    fullName: 'Dr Lipo+',
    alias: 'Dr Lipo+',
    category: 'Metabolic Research',
    researchCategory: 'Localized metabolic-pathway research',
    structureType: 'Compound blend',
    strength: 0,
    unit: 'ml',
    formatType: 'injectable blend',
    summaryShort: 'Compound blend listed for localized metabolic-pathway research.',
    summaryFull: 'Dr Lipo+ is listed in the founder source sheet for research involving localized metabolic-pathway studies. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'warm coral',
    accentColorHex: '#C58B74',
  }),

  'fox04-10mg': createCatalogProduct({
    slug: 'fox04-10mg',
    displayName: 'FOXO4 10mg',
    fullName: 'FOXO4',
    alias: 'FOXO4',
    category: 'Cellular Health Research',
    researchCategory: 'Senolytic and longevity research',
    structureType: 'Research peptide',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    summaryShort: 'Research peptide listed for senescent-cell elimination and longevity studies.',
    summaryFull: 'FOXO4 is listed in the founder source sheet for research involving senescent-cell clearance and longevity-related pathways. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'steel violet',
    accentColorHex: '#7D7AA7',
  }),

  'glow-50-10-10': createCatalogProduct({
    slug: 'glow-50-10-10',
    displayName: 'GLOW 50/10/10',
    fullName: 'GLOW Blend',
    alias: 'GLOW',
    category: 'Dermatological Research',
    researchCategory: 'Skin elasticity and collagen-support research',
    structureType: 'Compound blend',
    strength: 0,
    unit: 'mg',
    formatType: 'blend',
    summaryShort: 'Blend listed for dermal-matrix and collagen-pathway research.',
    summaryFull: 'GLOW is listed in the founder source sheet for research involving dermal-matrix and collagen-related pathways. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'pearl blush',
    accentColorHex: '#C8A8B0',
  }),

  'hcg-5000iu': createCatalogProduct({
    slug: 'hcg-5000iu',
    displayName: 'HCG 5000iu',
    fullName: 'Human Chorionic Gonadotropin',
    alias: 'HCG',
    category: 'Endocrine Signaling Research',
    researchCategory: 'Hormone signaling research',
    structureType: 'Glycoprotein hormone',
    strength: 5000,
    unit: 'iu',
    formatType: 'vial',
    summaryShort: 'Hormone research item listed for endocrine-signaling studies.',
    summaryFull: 'HCG is listed in the founder source sheet for research involving endocrine-signaling pathways. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'deep cobalt',
    accentColorHex: '#5C76B3',
  }),

  'hgh-12iu': createCatalogProduct({
    slug: 'hgh-12iu',
    displayName: 'HGH 12iu',
    fullName: 'Human Growth Hormone',
    alias: 'HGH',
    category: 'Endocrine Signaling Research',
    researchCategory: 'Growth-hormone pathway research',
    structureType: 'Research peptide',
    strength: 12,
    unit: 'iu',
    formatType: 'vial',
    summaryShort: 'Growth-hormone pathway listing for laboratory reference and documentation.',
    summaryFull: 'HGH is listed in the founder source sheet for research catalog completeness. This page is intended for scientific cataloging and laboratory reference only.',
    accentColor: 'soft cobalt',
    accentColorHex: '#6E86BC',
    variantGroup: 'hgh',
    variantLabel: '12iu',
  }),

  'hgh-24iu': createCatalogProduct({
    slug: 'hgh-24iu',
    displayName: 'HGH 24iu',
    fullName: 'Human Growth Hormone',
    alias: 'HGH',
    category: 'Endocrine Signaling Research',
    researchCategory: 'Growth-hormone pathway research',
    structureType: 'Research peptide',
    strength: 24,
    unit: 'iu',
    formatType: 'vial',
    summaryShort: 'Growth-hormone pathway listing for laboratory reference and documentation.',
    summaryFull: 'HGH is listed in the founder source sheet for research catalog completeness. This page is intended for scientific cataloging and laboratory reference only.',
    accentColor: 'soft cobalt',
    accentColorHex: '#6E86BC',
    variantGroup: 'hgh',
    variantLabel: '24iu',
  }),

  'hgh36-36iu': createCatalogProduct({
    slug: 'hgh36-36iu',
    displayName: 'HGH 36iu',
    fullName: 'Human Growth Hormone',
    alias: 'HGH',
    category: 'Endocrine Signaling Research',
    researchCategory: 'Growth-hormone pathway research',
    structureType: 'Research peptide',
    strength: 36,
    unit: 'iu',
    formatType: 'vial',
    summaryShort: 'Growth-hormone pathway item listed in the founder source sheet pending fuller copy confirmation.',
    summaryFull: 'HGH is listed in the founder source sheet and is included here for catalog completeness while final render and expanded copy are pending. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'soft cobalt',
    accentColorHex: '#6E86BC',
    variantGroup: 'hgh',
    variantLabel: '36iu',
  }),

  'igf-1-10mg': createCatalogProduct({
    slug: 'igf-1-10mg',
    displayName: 'IGF-1 LR3 1mg',
    fullName: 'Insulin-like Growth Factor 1 LR3',
    alias: 'IGF-1',
    category: 'Endocrine Signaling Research',
    researchCategory: 'Growth-factor signaling research',
    structureType: 'Growth factor',
    strength: 1,
    unit: 'mg',
    formatType: 'vial',
    summaryShort: 'Growth-factor listing referenced for anabolic signaling and growth-factor research.',
    summaryFull: 'IGF-1 is listed in the founder source sheet for research involving anabolic signaling and growth-factor pathways. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'storm blue',
    accentColorHex: '#6A86A6',
  }),

  'kiss-10mg': createCatalogProduct({
    slug: 'kiss-10mg',
    displayName: 'KISS 10mg',
    fullName: 'Kisspeptin',
    alias: 'KISS',
    category: 'Endocrine Signaling Research',
    researchCategory: 'Neuroendocrine and sex-hormone research',
    structureType: 'Peptide hormone',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    summaryShort: 'Peptide hormone listed for neuroendocrine and sex-hormone signaling research.',
    summaryFull: 'Kisspeptin is listed in the founder source sheet for research involving neuroendocrine activity and sex-hormone signaling pathways. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'orchid slate',
    accentColorHex: '#8A79A6',
  }),

  'klow-50-10-10-10': createCatalogProduct({
    slug: 'klow-50-10-10-10',
    displayName: 'KLOW 50/10/10',
    fullName: 'KLOW Blend',
    alias: 'KLOW',
    category: 'Inflammatory Research',
    researchCategory: 'Inflammation and tissue-support research',
    structureType: 'Compound blend',
    strength: 0,
    unit: 'mg',
    formatType: 'blend',
    summaryShort: 'Blend listed in the founder source sheet pending final render and full formulation copy.',
    summaryFull: 'KLOW is listed in the founder source sheet and is included here for catalog completeness while final render and expanded copy are pending. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'dusty green',
    accentColorHex: '#7FA097',
  }),

  'lipo-c-20ml': createCatalogProduct({
    slug: 'lipo-c-20ml',
    displayName: 'Lipo C 20ml',
    fullName: 'Lipo C',
    alias: 'Lipo C',
    category: 'Metabolic Research',
    researchCategory: 'Fat-metabolism and liver-support research',
    structureType: 'Compound blend',
    strength: 20,
    unit: 'ml',
    formatType: 'bottle',
    summaryShort: 'Blend listed for metabolic and hepatic-pathway research.',
    summaryFull: 'Lipo C is listed in the founder source sheet for research involving metabolic and hepatic-pathway studies. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'amber gold',
    accentColorHex: '#B89461',
  }),

  'll-37-5mg': createCatalogProduct({
    slug: 'll-37-5mg',
    displayName: 'LL-37 5mg',
    fullName: 'LL-37',
    alias: 'LL-37',
    category: 'Immunomodulation Research',
    researchCategory: 'Innate immunity and infection-response research',
    structureType: 'Antimicrobial peptide',
    strength: 5,
    unit: 'mg',
    formatType: 'vial',
    summaryShort: 'Antimicrobial peptide listed for immunity and infection-response research.',
    summaryFull: 'LL-37 is listed in the founder source sheet for research involving innate immunity and infection-response pathways. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'mineral green',
    accentColorHex: '#6F9B80',
  }),

  'mots-c-10mg': createCatalogProduct({
    slug: 'mots-c-10mg',
    displayName: 'Mots-C 10mg',
    fullName: 'Mots-C',
    alias: 'Mots-C',
    category: 'Mitochondrial Research',
    researchCategory: 'Mitochondrial peptide and metabolic research',
    structureType: 'Mitochondrial-encoded peptide',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    summaryShort: 'Mitochondrial peptide listed for mitochondrial peptide and metabolic research.',
    summaryFull: 'MOTS-C 10mg is listed in the founder source sheet for research involving mitochondrial signaling, metabolic pathways, and cellular energy regulation. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'deep teal',
    accentColorHex: '#4A7A7A',
    variantGroup: 'motsc',
    variantLabel: '10mg',
  }),

  'pinealon-10mg': createCatalogProduct({
    slug: 'pinealon-10mg',
    displayName: 'Pinealon 10mg',
    fullName: 'Pinealon',
    alias: 'Pinealon',
    category: 'Neuropeptide Research',
    researchCategory: 'Neuroprotection and circadian-rhythm research',
    structureType: 'Tripeptide',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    summaryShort: 'Tripeptide listed for neuroprotection, cognition, and circadian-rhythm research.',
    summaryFull: 'Pinealon is listed in the founder source sheet for research involving neuroprotection, cognitive support, and circadian-rhythm regulation. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'lavender steel',
    accentColorHex: '#8C8CB3',
  }),

  'primo100-10ml': createCatalogProduct({
    slug: 'primo100-10ml',
    displayName: 'Primo100 10ml',
    fullName: 'Primo100',
    alias: 'Primo100',
    category: 'Endocrine Signaling Research',
    researchCategory: 'Muscle-preservation and performance research',
    structureType: 'Research compound',
    strength: 10,
    unit: 'ml',
    formatType: 'vial',
    summaryShort: 'Research compound listed for muscle-preservation and performance-enhancement studies.',
    summaryFull: 'Primo100 is listed in the founder source sheet for research involving anabolic and endocrine-signaling pathways. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'slate bronze',
    accentColorHex: '#8A7A6E',
  }),

  'selank-10mg': createCatalogProduct({
    slug: 'selank-10mg',
    displayName: 'Selank 10mg',
    fullName: 'Selank',
    alias: 'Selank',
    category: 'Neuropeptide Research',
    researchCategory: 'Neuropeptide signaling and immune-response research',
    structureType: 'Synthetic peptide',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    summaryShort: 'Synthetic peptide listed for neuropeptide signaling and immune-response research.',
    summaryFull: 'Selank is listed in the founder source sheet for research involving neuropeptide signaling, stress-response pathways, and immune-function studies. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'cool violet',
    accentColorHex: '#7A88B5',
  }),

  'semax-10mg': createCatalogProduct({
    slug: 'semax-10mg',
    displayName: 'Semax 10mg',
    fullName: 'Semax',
    alias: 'Semax',
    category: 'Neuropeptide Research',
    researchCategory: 'Neuroprotection and memory research',
    structureType: 'Synthetic peptide',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    summaryShort: 'Synthetic peptide listed for neuroprotection and memory-pathway research.',
    summaryFull: 'Semax is listed in the founder source sheet for research involving neuroprotection, memory pathways, and cognitive-function studies. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'blue violet',
    accentColorHex: '#7484C6',
  }),

  'slu-pp-332-10mg': createCatalogProduct({
    slug: 'slu-pp-332-10mg',
    displayName: 'SLU-PP-332 10mg',
    fullName: 'SLU-PP-332',
    alias: 'SLU-PP',
    category: 'Metabolic Research',
    researchCategory: 'Metabolic function and energy-expenditure research',
    structureType: 'Research compound',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    summaryShort: 'Research compound listed for metabolic-function and energy-expenditure studies.',
    summaryFull: 'SLU-PP-332 is listed in the founder source sheet for research involving metabolic function and energy-expenditure pathways. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'electric indigo',
    accentColorHex: '#6B73C9',
    variantGroup: 'slupp',
    variantLabel: '10mg',
  }),

  'slu-pp-332-30mg': createCatalogProduct({
    slug: 'slu-pp-332-30mg',
    displayName: 'SLU-PP-332 30mg',
    fullName: 'SLU-PP-332',
    alias: 'SLU-PP',
    category: 'Metabolic Research',
    researchCategory: 'Metabolic function and energy-expenditure research',
    structureType: 'Research compound',
    strength: 30,
    unit: 'mg',
    formatType: 'vial',
    summaryShort: 'Research compound listed for metabolic-function and energy-expenditure studies.',
    summaryFull: 'SLU-PP-332 is listed in the founder source sheet for research involving metabolic function and energy-expenditure pathways. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'electric indigo',
    accentColorHex: '#6B73C9',
    variantGroup: 'slupp',
    variantLabel: '30mg',
  }),

  'ss-31-10mg': createCatalogProduct({
    slug: 'ss-31-10mg',
    displayName: 'SS-31 10mg',
    fullName: 'SS-31 (Elamipretide)',
    alias: 'SS-31',
    category: 'Mitochondrial Research',
    researchCategory: 'Mitochondrial targeting and oxidative-stress research',
    structureType: 'Short cationic peptide',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    summaryShort: 'Mitochondrial-targeting peptide listed for energy-production and oxidative-stress research.',
    summaryFull: 'SS-31 10mg is listed in the founder source sheet for research involving mitochondrial function, energy production, and oxidative-stress pathways. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'forest teal',
    accentColorHex: '#3A6A6A',
    variantGroup: 'ss31',
    variantLabel: '10mg',
  }),

  'ss-31-5mg': createCatalogProduct({
    slug: 'ss-31-5mg',
    displayName: 'SS-31 5mg',
    fullName: 'SS-31 (Elamipretide)',
    alias: 'SS-31',
    category: 'Mitochondrial Research',
    researchCategory: 'Mitochondrial targeting and oxidative-stress research',
    structureType: 'Short cationic peptide',
    strength: 5,
    unit: 'mg',
    formatType: 'vial',
    status: 'incoming',
    summaryShort: 'Mitochondrial-targeting peptide listed for energy-production and oxidative-stress research.',
    summaryFull: 'SS-31 is commonly referenced in mitochondrial research involving energy production and oxidative-stress pathways. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'forest teal',
    accentColorHex: '#3A6A6A',
    variantGroup: 'ss31',
    variantLabel: '5mg',
  }),

  'ss-31-30mg': createCatalogProduct({
    slug: 'ss-31-30mg',
    displayName: 'SS-31 30mg',
    fullName: 'SS-31 (Elamipretide)',
    alias: 'SS-31',
    category: 'Mitochondrial Research',
    researchCategory: 'Mitochondrial targeting and oxidative-stress research',
    structureType: 'Short cationic peptide',
    strength: 30,
    unit: 'mg',
    formatType: 'vial',
    status: 'incoming',
    summaryShort: 'Mitochondrial-targeting peptide listed for energy-production and oxidative-stress research.',
    summaryFull: 'SS-31 is commonly referenced in mitochondrial research involving energy production and oxidative-stress pathways. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'forest teal',
    accentColorHex: '#3A6A6A',
    variantGroup: 'ss31',
    variantLabel: '30mg',
  }),

  'ss-31-40mg': createCatalogProduct({
    slug: 'ss-31-40mg',
    displayName: 'SS-31 40mg',
    fullName: 'SS-31 (Elamipretide)',
    alias: 'SS-31',
    category: 'Mitochondrial Research',
    researchCategory: 'Mitochondrial targeting and oxidative-stress research',
    structureType: 'Short cationic peptide',
    strength: 40,
    unit: 'mg',
    formatType: 'vial',
    status: 'incoming',
    summaryShort: 'Mitochondrial-targeting peptide listed for energy-production and oxidative-stress research.',
    summaryFull: 'SS-31 is commonly referenced in mitochondrial research involving energy production and oxidative-stress pathways. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'forest teal',
    accentColorHex: '#3A6A6A',
    variantGroup: 'ss31',
    variantLabel: '40mg',
  }),

  'tc250-10ml': createCatalogProduct({
    slug: 'tc250-10ml',
    displayName: 'TC250 10ml',
    fullName: 'TC250',
    alias: 'TC250',
    category: 'Endocrine Signaling Research',
    researchCategory: 'Hormone-replacement research',
    structureType: 'Research compound',
    strength: 10,
    unit: 'ml',
    formatType: 'vial',
    summaryShort: 'Research compound listed for testosterone-replacement and hormone-signaling studies.',
    summaryFull: 'TC250 is listed in the founder source sheet for research involving testosterone-replacement and endocrine-signaling pathways. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'slate blue',
    accentColorHex: '#6A7CA4',
  }),

  'tesamor-10mg': createCatalogProduct({
    slug: 'tesamor-10mg',
    displayName: 'Tesamor 10mg',
    fullName: 'Tesamorelin',
    alias: 'TESAMOR',
    category: 'Metabolic Research',
    researchCategory: 'Metabolic-pathway and endocrine signaling research',
    structureType: 'Synthetic peptide analog',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    summaryShort: 'Synthetic peptide analog listed for metabolic-pathway and endocrine-signaling research.',
    summaryFull: 'Tesamorelin is listed in the founder source sheet for research involving metabolic-function and endocrine-signaling pathways. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'sand gold',
    accentColorHex: '#B79A66',
  }),

  'tirz-10mg': createCatalogProduct({
    slug: 'tirz-10mg',
    displayName: 'TIRZ 10mg',
    fullName: 'Tirzepatide',
    alias: 'TIRZ',
    category: 'Metabolic Research',
    researchCategory: 'Dual incretin receptor research',
    structureType: 'Synthetic peptide analog',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    status: 'incoming',
    summaryShort: 'Synthetic peptide analog commonly grouped in dual incretin receptor research.',
    summaryFull: 'Tirzepatide is generally classified in metabolic and incretin receptor research catalogs. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'cool cyan-blue',
    accentColorHex: '#4A8FC4',
    variantGroup: 'tirz',
    variantLabel: '10mg',
  }),

  'tirz-20mg': createCatalogProduct({
    slug: 'tirz-20mg',
    displayName: 'TIRZ 20mg',
    fullName: 'Tirzepatide',
    alias: 'TIRZ',
    category: 'Metabolic Research',
    researchCategory: 'Dual incretin receptor research',
    structureType: 'Synthetic peptide analog',
    strength: 20,
    unit: 'mg',
    formatType: 'vial',
    summaryShort: 'Synthetic peptide analog listed for dual incretin receptor research.',
    summaryFull: 'Tirzepatide is listed in the founder source sheet for research involving incretin receptor signaling and metabolic-pathway studies. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'cool cyan-blue',
    accentColorHex: '#4A8FC4',
    variantGroup: 'tirz',
    variantLabel: '20mg',
  }),

  'tirz-40mg': createCatalogProduct({
    slug: 'tirz-40mg',
    displayName: 'TIRZ 40mg',
    fullName: 'Tirzepatide',
    alias: 'TIRZ',
    category: 'Metabolic Research',
    researchCategory: 'Dual incretin receptor research',
    structureType: 'Synthetic peptide analog',
    strength: 40,
    unit: 'mg',
    formatType: 'vial',
    status: 'incoming',
    summaryShort: 'Synthetic peptide analog commonly grouped in dual incretin receptor research.',
    summaryFull: 'Tirzepatide is generally classified in metabolic and incretin receptor research catalogs. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'cool cyan-blue',
    accentColorHex: '#4A8FC4',
    variantGroup: 'tirz',
    variantLabel: '40mg',
  }),

  'tirz-50mg': createCatalogProduct({
    slug: 'tirz-50mg',
    displayName: 'TIRZ 50mg',
    fullName: 'Tirzepatide',
    alias: 'TIRZ',
    category: 'Metabolic Research',
    researchCategory: 'Dual incretin receptor research',
    structureType: 'Synthetic peptide analog',
    strength: 50,
    unit: 'mg',
    formatType: 'vial',
    status: 'incoming',
    summaryShort: 'Synthetic peptide analog commonly grouped in dual incretin receptor research.',
    summaryFull: 'Tirzepatide is generally classified in metabolic and incretin receptor research catalogs. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'cool cyan-blue',
    accentColorHex: '#4A8FC4',
    variantGroup: 'tirz',
    variantLabel: '50mg',
  }),

  'vesugen-20mg': createCatalogProduct({
    slug: 'vesugen-20mg',
    displayName: 'Vesugen 20mg',
    fullName: 'Vesugen',
    alias: 'Vesugen',
    category: 'Bio-Regulator Research',
    researchCategory: 'Peptide bioregulator research',
    structureType: 'Peptide bioregulator',
    strength: 20,
    unit: 'mg',
    formatType: 'vial',
    summaryShort: 'Peptide bioregulator listed as a 20mg research-format entry for laboratory reference.',
    summaryFull: 'Vesugen is currently grouped in the FlexMed bio-regulator catalog as a 20mg research-format listing for scientific cataloging and laboratory reference only.',
    accentColor: 'seafoam blue',
    accentColorHex: '#7AAAB7',
  }),

  'livogen': createCatalogProduct({
    slug: 'livogen',
    displayName: 'Livagen 20mg',
    fullName: 'Livagen',
    alias: 'Livagen',
    category: 'Bio-Regulator Research',
    researchCategory: 'Peptide bioregulator research',
    structureType: 'Peptide bioregulator',
    strength: 20,
    unit: 'mg',
    formatType: 'vial',
    status: 'incoming',
    summaryShort: 'Peptide bioregulator listed as a 20mg incoming research-format entry.',
    summaryFull: 'Livagen is included in the FlexMed bio-regulator catalog as a 20mg incoming listing for scientific cataloging and laboratory reference only.',
    accentColor: 'seafoam blue',
    accentColorHex: '#7AAAB7',
  }),

  'bronchogen': createCatalogProduct({
    slug: 'bronchogen',
    displayName: 'Bronchogen 20mg',
    fullName: 'Bronchogen',
    alias: 'Bronchogen',
    category: 'Bio-Regulator Research',
    researchCategory: 'Peptide bioregulator research',
    structureType: 'Peptide bioregulator',
    strength: 20,
    unit: 'mg',
    formatType: 'vial',
    status: 'incoming',
    summaryShort: 'Peptide bioregulator listed as a 20mg incoming research-format entry.',
    summaryFull: 'Bronchogen is included in the FlexMed bio-regulator catalog as a 20mg incoming listing for scientific cataloging and laboratory reference only.',
    accentColor: 'seafoam blue',
    accentColorHex: '#7AAAB7',
  }),

  'testogen-20mg': createCatalogProduct({
    slug: 'testogen-20mg',
    displayName: 'Testagen 20mg',
    fullName: 'Testagen',
    alias: 'Testagen',
    category: 'Bio-Regulator Research',
    researchCategory: 'Peptide bioregulator research',
    structureType: 'Peptide bioregulator',
    strength: 20,
    unit: 'mg',
    formatType: 'vial',
    status: 'incoming',
    summaryShort: 'Peptide bioregulator listed as a 20mg incoming research-format entry.',
    summaryFull: 'Testagen is included in the FlexMed bio-regulator catalog as a 20mg incoming listing for scientific cataloging and laboratory reference only.',
    accentColor: 'seafoam blue',
    accentColorHex: '#7AAAB7',
  }),

  'vip-10mg': createCatalogProduct({
    slug: 'vip-10mg',
    displayName: 'VIP 10mg',
    fullName: 'Vasoactive Intestinal Peptide',
    alias: 'VIP',
    category: 'Inflammatory Research',
    researchCategory: 'Vascular, circulation, and inflammation research',
    structureType: 'Neuropeptide hormone',
    strength: 10,
    unit: 'mg',
    formatType: 'vial',
    status: 'out_of_stock',
    summaryShort: 'Neuropeptide hormone listed for vascular signaling and inflammatory-pathway research.',
    summaryFull: 'VIP is listed in the founder source sheet for research involving vascular signaling, inflammatory pathways, and cellular communication studies. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'aqua blue',
    accentColorHex: '#67A7B8',
  }),

  'wolver-bpc-tb500': createCatalogProduct({
    slug: 'wolver-bpc-tb500',
    displayName: 'Wolver-BPC/TB500',
    fullName: 'BPC-157 + TB500',
    alias: 'Wolverine',
    category: 'Inflammatory Research',
    researchCategory: 'Muscle, tendon, and joint-repair research',
    structureType: 'Synthetic peptide combination',
    strength: 0,
    unit: 'mg',
    formatType: 'blend',
    summaryShort: 'Peptide blend listed for connective-tissue and repair-pathway research.',
    summaryFull: 'Wolver-BPC/TB500 is listed in the founder source sheet for research involving connective-tissue and repair-related pathways. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'steel green',
    accentColorHex: '#6D8E86',
  }),

  'snooze-zen-10ml': createCatalogProduct({
    slug: 'snooze-zen-10ml',
    displayName: 'Snooze Zen 10ml',
    fullName: 'Snooze Zen',
    alias: 'SNOOZE ZEN',
    category: 'Neuropeptide Research',
    researchCategory: 'Sleep-support blend research',
    structureType: 'Compound blend',
    strength: 10,
    unit: 'ml',
    formatType: 'bottle',
    summaryShort: 'Compound blend listed for neuropeptide and circadian-pathway research.',
    summaryFull: 'Snooze Zen is listed in the founder source sheet as a compound blend containing GABA 100, L-histidine, L-theanine, taurine, melatonin 2, and lidocaine 0.2. This page is intended for cataloging and research-reference purposes only.',
    accentColor: 'midnight lavender',
    accentColorHex: '#6E74A8',
  }),

  // ─── ON HOLD — DO NOT BUILD ─────────────────────────────────
  // Not included in PRODUCTS record.
  // HGH36 UTH, SLU-PP-5, WOLVERINE-20 are on hold pending clarification.
}

export const PRODUCT_CATEGORIES = [
  'All',
  'Endocrine Signaling Research',
  'Metabolic Research',
  'Mitochondrial Research',
  'Neuropeptide Research',
  'Bio-Regulator Research',
  'Antioxidant Research',
  'Dermatological Research',
  'Immunomodulation Research',
  'Telomere Research',
  'Cellular Health Research',
  'Cell Cycle Research',
  'Inflammatory Research',
  'Pigmentation Research',
]

// PUBLIC_SLUGS — the sole source of truth for public visibility.
// Includes live products plus placeholder-backed items so the founder can
// see unfinished catalog coverage directly on the public grid.
export const PUBLIC_SLUGS = [
  '5-amino-1-50mg',
  'adalink',
  'adamax-10mg',
  'aodc-5mg',
  'ara-290-10mg',
  'bronchogen',
  'cagri-5mg',
  'cjc-ipa-10mg',
  'cartalax-20mg',
  'dsip-5mg',
  'dsip-10mg',
  'epithalon-10mg',
  'epithalon-50mg',
  'fox04-10mg',
  'glow-50-10-10',
  'glutathione-500',
  'glutathione-1000',
  'hgh36-36iu',
  'igf-1-10mg',
  'kiss-10mg',
  'kpv-10mg',
  'klow-50-10-10-10',
  'livogen',
  'testogen-20mg',
  'll-37-5mg',
  'mel-2-10mg',
  'mots-c-10mg',
  'mots-c-40mg',
  'nad-plus-500',
  'pe-22-28-wwb-10mg',
  'pinealon-10mg',
  'reta-20mg',
  'reta-30mg',
  'selank-10mg',
  'semax-10mg',
  'snap-8-10mg',
  'slu-pp-332-10mg',
  'ss-31-10mg',
  'ss-31-50mg',
  'tesamor-10mg',
  'thy-a1-10mg',
  'tirz-10mg',
  'tirz-15mg',
  'tirz-20mg',
  'tirz-30mg',
  'tirz-40mg',
  'vesugen-20mg',
  'wolver-bpc-tb500',
] as const

export const CONFIRMED_SLUGS = [
  '5-amino-1-50mg',
  'adalink',
  'adamax-10mg',
  'aodc-5mg',
  'ara-290-10mg',
  'bronchogen',
  'cartalax-20mg',
  'cjc-ipa-10mg',
  'cagri-5mg',
  'dsip-5mg',
  'dsip-10mg',
  'epithalon-10mg',
  'epithalon-50mg',
  'fox04-10mg',
  'glow-50-10-10',
  'glutathione-500',
  'glutathione-1000',
  'hgh36-36iu',
  'igf-1-10mg',
  'kiss-10mg',
  'kpv-10mg',
  'klow-50-10-10-10',
  'livogen',
  'testogen-20mg',
  'll-37-5mg',
  'mel-2-10mg',
  'mots-c-10mg',
  'mots-c-40mg',
  'nad-plus-500',
  'pe-22-28-wwb-10mg',
  'pinealon-10mg',
  'reta-20mg',
  'reta-30mg',
  'selank-10mg',
  'semax-10mg',
  'snap-8-10mg',
  'slu-pp-332-10mg',
  'ss-31-10mg',
  'ss-31-50mg',
  'tesamor-10mg',
  'thy-a1-10mg',
  'tirz-10mg',
  'tirz-15mg',
  'tirz-20mg',
  'tirz-30mg',
  'tirz-40mg',
  'vesugen-20mg',
  'wolver-bpc-tb500',
]

export const CATALOG_SLUGS = [
  '5-amino-1-50mg',
  'adalink',
  'adamax-10mg',
  'aodc-5mg',
  'ara-290-10mg',
  'bronchogen',
  'cagri-5mg',
  'cartalax-20mg',
  'cjc-ipa-10mg',
  'dsip-5mg',
  'dsip-10mg',
  'epithalon-10mg',
  'epithalon-50mg',
  'fox04-10mg',
  'glow-50-10-10',
  'glutathione-500',
  'hgh36-36iu',
  'igf-1-10mg',
  'kiss-10mg',
  'kpv-10mg',
  'klow-50-10-10-10',
  'livogen',
  'testogen-20mg',
  'll-37-5mg',
  'mel-2-10mg',
  'mots-c-10mg',
  'nad-plus-500',
  'pe-22-28-wwb-10mg',
  'pinealon-10mg',
  'reta-20mg',
  'reta-30mg',
  'selank-10mg',
  'semax-10mg',
  'snap-8-10mg',
  'slu-pp-332-10mg',
  'ss-31-10mg',
  'tesamor-10mg',
  'thy-a1-10mg',
  'tirz-10mg',
  'tirz-15mg',
  'tirz-20mg',
  'tirz-30mg',
  'tirz-40mg',
  'vesugen-20mg',
  'wolver-bpc-tb500',
] as const

export const NEEDS_CONFIRMATION_SLUGS = [
  'pnc-27-5mg',
  'pt-141-10mg',
]

export const ALL_PRODUCT_SLUGS = [...CONFIRMED_SLUGS, ...NEEDS_CONFIRMATION_SLUGS]

export const BIO_REGULATOR_SLUGS = new Set([
  'vesugen-20mg',
  'livogen',
  'bronchogen',
  'cartalax-20mg',
  'testogen-20mg',
])

export function getProductsByCategory(category: string): Product[] {
  const all = getAllPublicProducts()
  if (category === 'All') return all
  return all.filter((p) => p.category === category)
}

export function getAllPublicProducts(): Product[] {
  return CATALOG_SLUGS.map((slug) => PRODUCTS[slug]).filter(Boolean)
}

export function getCatalogDisplayProducts(): Product[] {
  const seenVariantGroups = new Set<string>()

  return getAllPublicProducts().filter((product) => {
    if (!product.variantGroup) return true
    if (seenVariantGroups.has(product.variantGroup)) return false
    seenVariantGroups.add(product.variantGroup)
    return true
  })
}

export function isBioRegulator(productOrSlug: Product | string): boolean {
  const slug = typeof productOrSlug === 'string' ? productOrSlug : productOrSlug.slug
  return BIO_REGULATOR_SLUGS.has(slug)
}

export function getPendingConfirmationProducts(): Product[] {
  return Object.values(PRODUCTS).filter((p) => p.publishStatus === 'needs_confirmation')
}

export function getAdminCatalogProducts(): Product[] {
  // Admin view: includes confirmed + needs_confirmation, excludes only on_hold
  return Object.values(PRODUCTS).filter((p) => p.publishStatus !== 'on_hold')
}

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS[slug]
}

export function getConfirmedProducts(): Product[] {
  return Object.values(PRODUCTS).filter((p) => p.publishStatus === 'confirmed')
}

export function getFeaturedProducts(): Product[] {
  return SITE_SETTINGS.featuredProductSlugs.map((s) => PRODUCTS[s]).filter(Boolean)
}

export const PRODUCT_VARIANT_FAMILIES: Record<string, string[]> = {
  glutathione: ['glutathione-500', 'glutathione-1000'],
  tirz: ['tirz-10mg', 'tirz-15mg', 'tirz-20mg', 'tirz-30mg', 'tirz-40mg'],
  hgh: ['hgh-12iu', 'hgh-24iu', 'hgh36-36iu'],
  motsc: ['mots-c-10mg', 'mots-c-40mg'],
  reta: ['reta-20mg', 'reta-30mg'],
  slupp: ['slu-pp-332-10mg'],
  ss31: ['ss-31-10mg', 'ss-31-50mg'],
  nadplus: ['nad-plus-500'],
  dsip: ['dsip-5mg', 'dsip-10mg'],
  epithalon: ['epithalon-10mg', 'epithalon-50mg'],
}

export function getProductVariants(productOrSlug: Product | string): Product[] {
  const product =
    typeof productOrSlug === 'string' ? PRODUCTS[productOrSlug] : productOrSlug

  if (!product?.variantGroup) return []

  return (PRODUCT_VARIANT_FAMILIES[product.variantGroup] ?? [])
    .map((slug) => PRODUCTS[slug])
    .filter(Boolean)
}

// ─── Atmospheric Banner Assets ─────────────────────────────────
// Wide 4:1 banner visuals for product detail page atmosphere.
// heroBanner: top-of-page hero support (high energy, full opacity)
// sectionDivider: between sections at lower opacity
// Per-product banners can override by adding to this map.
// ────────────────────────────────────────────────────────────────

export const BANNER_ASSETS: Record<string, { heroBanner: string; sectionDivider: string }> = {
  // Default banners — all products share these unless overridden
  __default: {
    heroBanner: '/banners/hero-banner-4x1.png',
    sectionDivider: '/banners/section-divider-4x1.png',
  },
  // Per-product overrides go here when generated:
  // 'cjc-ipa-10mg': { heroBanner: '/banners/cjc-ipa-hero.png', sectionDivider: '/banners/cjc-ipa-divider.png' },
}

export function getProductBannerSrc(slug: string, type: 'heroBanner' | 'sectionDivider'): string {
  if (BANNER_ASSETS[slug]?.[type]) {
    return BANNER_ASSETS[slug][type]
  }
  return BANNER_ASSETS.__default[type]
}

// ─── Image Resolution ──────────────────────────────────────────
// Centralized image resolution for all product imagery.
// Uses PRODUCT_IMAGES map as the source of truth for file paths.
// Falls back to product.image for any products not yet in the map.
// hoverSpinFrames come from PRODUCT_IMAGES — add to that map to enable.
// ──────────────────────────────────────────────────────────────

// ─── Own-asset guard ──────────────────────────────────────────
// Renders and uploaded photos live under the product's own slug
// (/products/<slug>/… or /api/catalog-assets/image/<slug>). A variant
// must never show a sibling's asset: when its own is missing it gets
// the generic placeholder, not another SKU's label.
// ───────────────────────────────────────────────────────────────

const PRODUCT_ASSET_OWNER_PATTERNS = [/^\/api\/catalog-assets\/image\/([^/?#]+)/, /^\/products\/([^/?#]+)\//]

/** The slug an asset path belongs to, or null for shared assets such as the placeholder. */
export function getProductAssetOwnerSlug(src: string | null | undefined): string | null {
  if (!src) return null
  for (const pattern of PRODUCT_ASSET_OWNER_PATTERNS) {
    const match = src.match(pattern)
    if (match) return match[1]
  }
  return null
}

/** True when the asset is the product's own or is not tied to any product. */
export function isOwnProductAsset(src: string | null | undefined, slug: string): boolean {
  const owner = getProductAssetOwnerSlug(src)
  return owner === null || owner === slug
}

export function getProductImageSrc(product: Product): string {
  const ownImage = isOwnProductAsset(product.image, product.slug) ? product.image : ''
  if (ownImage && !ownImage.includes('REQUIRED') && ownImage !== PLACEHOLDER_PRODUCT_IMAGE) {
    return ownImage
  }
  const staticFront = PRODUCT_IMAGES[product.slug]?.front
  if (staticFront && isOwnProductAsset(staticFront, product.slug)) {
    return staticFront
  }
  if (PLACEHOLDER_RENDER_SLUGS.includes(product.slug as (typeof PLACEHOLDER_RENDER_SLUGS)[number])) {
    return PLACEHOLDER_PRODUCT_IMAGE
  }
  if (ownImage && !ownImage.includes('REQUIRED')) {
    return ownImage
  }
  return PLACEHOLDER_PRODUCT_IMAGE
}

export function getProductSideSrc(product: Product): string {
  const side = PRODUCT_IMAGES[product.slug]?.side
  return side && isOwnProductAsset(side, product.slug) ? side : ''
}

export function getProductHoverSpinFrames(product: Product): string[] {
  return (PRODUCT_IMAGES[product.slug]?.hoverSpinFrames ?? []).filter((frame) => isOwnProductAsset(frame, product.slug))
}

export function isPlaceholderProductImage(product: Product): boolean {
  return getProductImageSrc(product) === PLACEHOLDER_PRODUCT_IMAGE
}

export function usesPhotoStyleProductImage(product: Product): boolean {
  const src = getProductImageSrc(product)
  if (!src || src === PLACEHOLDER_PRODUCT_IMAGE) return true
  if (TRANSPARENT_CUTOUT_IMAGE_SLUGS.has(product.slug)) return false
  return true
}
